---
# tasks file for mariadb
- name: Install mariaDB server and co
  package:
    name:
      - mariadb-server
      - php-mysqlnd
      - python3-dev
      - python3-pip
      - python3-setuptools
      - python3-pymysql
      - mariadb-client
    state: present

- name: Install pip PyMySQL package
  pip:
    name: PyMySQL
    state: present

- name: start mariadb
  service:
    name: mariadb
    enabled: true
    state: started


# - name: Set ~/.my.cnf
#   template: 
#     src: ~/DevOps/Github_Projects/Master_DB_servers/Master_roles/files/my.cnf.j2 
#     dest: /root/.my.cnf 
#     mode: 0700

# - name: Set mysql config file to bind amd share log with slave
#   template: 
#     src: ~/DevOps/Github_Projects/Master_DB_servers/Master_roles/templates/master_log.j2
#     dest: /etc/mysql/mariadb.conf.d/50-server.cnf
#     mode: 0700

# - name: Restart mysql
#   service:
#     name: mysql
#     state: restarted


# - name: Update mariaDB root password
#   mysql_user:
#     login_user: "{{ mysql_root_user }}"
#     login_unix_socket: /var/run/mysqld/mysqld.sock
#     user: "{{ mysql_root_user }}"
#     check_implicit_admin: true
#     password: "{{ mysql_root_password }}"
#     host: "{{item}}"
#   with_items:
#     - 127.0.0.1
#     -  ::1
#     - localhost  


# - name: Create replica database
#   mysql_db:
#     name: "{{replica_db_name}}"
#     state: present
#     login_user: "{{ mysql_root_user }}"
#     login_password: "{{mysql_root_password}}"

# - name: Create slave mysql user on Master node
#   mysql_user:
#     name: "{{replica_db_user}}"
#     password: "{{replica_db_password}}"
#     state: present
#     host: "{{ Slaves_IP }}"
#     priv: "*.*:REPLICATION SLAVE"
#     login_user: "{{ mysql_root_user }}"
#     login_password: "{{mysql_root_password}}"

