---
# tasks file for Slave_roles
- name: Install mariaDB server and co
  package:
    name:
      - mariadb-server
      - php-mysqlnd
      - python3-dev
      - python3-pip
      - python3-setuptools
      - python3-pymysql
      - mariadb-client
    state: present

- name: Install pip PyMySQL package
  pip:
    name: PyMySQL
    state: present

- name: start mariadb
  service:
    name: mariadb
    enabled: true
    state: started


# - name: Set ~/.my.cnf
#   template: 
#     src: ~/DevOps/Github_Projects/Master_DB_servers/Slave_roles/templates/my.cnf.j2 
#     dest: /root/.my.cnf 
#     mode: 0600

# - name: Set mysql config file to bind and share log with master node
#   template: 
#     src: ~/DevOps/Github_Projects/Master_DB_servers/Slave_roles/templates/slave_log.j2
#     dest: /etc/mysql/mariadb.conf.d/50-server.cnf
#     mode: 0600

# - name: Update mariaDB root password
#   mysql_user:
#     login_user: "{{ mysql_root_user }}"
#     login_unix_socket: /var/run/mysqld/mysqld.sock
#     user: "{{ mysql_root_user }}"
#     check_implicit_admin: true
#     password: "{{ mysql_root_password }}"
#     host: "{{item}}"
#   with_items:
#     - 127.0.0.1
#     -  ::1
#     - localhost  


# - name: Removes anonymous user account for localhost
#   mysql_user:
#     name: ''
#     host: hostname
#     state: absent
#     login_user: root
#     login_password: "{{mysql_root_password}}"

# - name: Stop mysql replica thread
#   mysql_replication:
#     mode: stopslave

# - name: Get primary binlog file name and binlog position
#   mysql_replication:
#     mode: getmaster


# - name: Change primary to primary server 192.168.50.7 and use binary log 'mysql-bin.000009' with position 4578
#   mysql_replication:
#     mode: changemaster
#     master_host: 192.168.50.7
#     master_log_file: mysql-bin.000009
#     master_log_pos: 4578

# - name: Dump all databases to hostname.sql(Slave) including master data
#   mysql_db:
#     state: dump
#     name: all
#     target: /tmp/dump.sql

# - name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
#   mysql_db:
#     state: import
#     name: all
#     target: /tmp/dump.sql
    

# - name: Start mysql replica thread
#   mysql_replication:
#     mode: startslave

# - name: Check replica status using port 3306
#   mysql_replication:
#     mode: getmaster
#     login_port: 3306

